task:
  name: Check Jekyll blog
  arm_container:
    matrix:
      - image: docker.io/openeuler/openeuler
      - image: docker.io/library/rockylinux:9
      - image: ruby:latest
  env_script: |
    uname -a
    cat /etc/os-release
  setup_script: |
    if [[ -x "$(command -v dnf)" ]]
    then
      dnf install -y ruby ruby-devel libffi-devel
      dnf group install -y "Development Tools"
    fi
    gem install jekyll bundler github-pages
  script: |
    echo "checking pull request #${CIRRUS_PR}"
    bundle exec jekyll build --verbose
