os: linux
dist: focal
arch:
  - arm64-graviton2
# - arm64
virt:
  - vm
# - lxd
language: ruby
rvm: 2.6
notifications:
  email: false
branches:
  only:
    - master
script: "bundle exec jekyll build --verbose"
