os: linux
dist: focal
arch:
  - arm64-graviton2
  - arm64
virt:
  - lxd
  - vm
group: edge
language: ruby
rvm: 2.6
script: "bundle exec jekyll build"
branches:
  only:
    - master
notifications:
  email: false
