name: Check Jekyll blog

on:
  pull_request:
    # Runs on any pull request to master
    branches: [ master ]

  workflow_dispatch:

jobs:
  check-on-openEuler:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        container-image: [ "docker.io/openeuler/openeuler",
                           "docker.io/library/rockylinux:9",
                           "ruby:latest"]
    container:
      image: ${{ matrix.container-image }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup
        run: |
          if [[ -x "$(command -v dnf)" ]]
          then
            dnf install -y ruby ruby-devel libffi-devel
            dnf group install -y "Development Tools"
          fi
          gem install jekyll bundler github-pages
      - name: Run
        run: |
          echo "checking pull request #${{ github.event.number }}"
          bundle exec jekyll build --verbose
